### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by jrobinson-uk** [raspberrypilearning/sensing-the-weather#7]
@LornaLynch Whilst waiting for the next Astro Pi resource (hopefully today) could you take a look at this scheme.

A recent(ish) snap shot is up on staging at https://staging.raspberrypi.org/learning/weather-station-1/

**Comment by bennuttall** [comment]
Someone just PR'd a typo so I don't know if copy editing was ever finished. Leaving this open.

**Comment by lauraclay** [comment]
A quick page through the history, which would have taken five minutes, reveals that Lorna edited this resource in July 2015. Since then, there have been a substantial number of commits from @jrobinson-uk and @MissPhilbin, which is likely where the copy has changed so much that mistakes were reintroduced. Can I request that if a resource has been changed by another team, it comes back to the copy editors? It would also help if commits weren't just named 'Update README.md' and so on, as this doesn't tell us anything at a glance about what has been changed.

Assigned Lorna to this at her request.

**Comment by MissPhilbin** [comment]
Thanks for your support, we will ensure we follow the correct procedure in future.
